spring:
  favicon:
    enabled: true
  application:
    name: KLT Converter
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8081
  servlet:
    context-path: /klt
